version: "3.9"

services:
  db:
    image: postgres:15
    container_name: artist_postgres
    restart: always
    environment:
      POSTGRES_USER: artist
      POSTGRES_PASSWORD: artistpwd
      POSTGRES_DB: artistdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: artist_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://artist:artistpwd@db:5432/artistdb
    depends_on:
      - db

volumes:
  postgres_data:
