name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend (FastAPI smoke)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Import check
        run: python -c "import fastapi, pydantic; print('backend ok')"
      - name: Endpoint smoke
        run: |
          python - <<'PY'
          import importlib
          m = importlib.import_module("app.main")
          assert m.health()["ok"] is True
          print("health ok")
          PY
      - name: Create listing smoke
        run: |
          python - <<'PY'
          from app.main import post_listing, schemas, list_listings
          from app.db import SessionLocal
          db = SessionLocal()
          post_listing(schemas.ListingIn(
              title="Test", description="Ok", price_from=10, city="Tashkent", category="music"
          ), db)
          assert len(list_listings(db)) >= 1
          print("create ok")
          PY


  frontend:
    name: Frontend (Next.js build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci || npm i
      - run: npm run build
