name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend (FastAPI smoke)
    runs-on: ubuntu-latest
    if: hashFiles('apps/backend/**') != ''
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn[standard] SQLAlchemy psycopg2-binary
      - name: Lint stub
        run: python -c "print('Backend OK')"

  frontend:
    name: Frontend (Next.js build)
    runs-on: ubuntu-latest
    if: hashFiles('apps/frontend/**') != ''
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "apps/frontend/package-lock.json"
      - name: Install
        run: npm ci || npm i
      - name: Build
        run: npm run build
