name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend (FastAPI smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke
        run: echo "Backend OK"

  frontend:
    name: Frontend (Next.js build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build stub
        run: echo "Frontend OK"

